# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call C function from Rcpp
#' 
#' Uses the convolve_c function inside of a C++ routine by Rcpp.
#' 
#' @param a,b A `numeric` vector.
#' 
#' @return 
#' A `numeric` vector of length \eqn{N_a + N_b}.
#' 
#' @examples
#' 
#' convolve_from_c(1:5, 5:1)
#' 
#' @export
convolve_from_c <- function(a, b) {
    .Call(`_cRcpp_convolve_from_c`, a, b)
}

#' Pure Rcpp Routine
#' 
#' Implements the convolution function as a _C++_ routine surfaced by _Rcpp_.
#' 
#' @param a,b A `numeric` vector.
#' 
#' @return 
#' A `numeric` vector of length \eqn{N_a + N_b}.
#' 
#' @examples
#' 
#' convolve_cpp(1:5, 5:1)
#' 
#' @export
convolve_cpp <- function(a, b) {
    .Call(`_cRcpp_convolve_cpp`, a, b)
}

